name: CI-PR

on:
  push:
    branches:
      - master # Only fire for commits on master branch
  pull_request:
    types: [opened, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
